# Generated by Django 5.0 on 2023-12-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(db_index=True, default='SafaWorld 339209', editable=False, unique=True),
        ),
    ]
